# Generated by Django 4.0.2 on 2022-04-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_author', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DdiDocument',
            fields=[
                ('id_doc', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_record', models.IntegerField()),
                ('title', models.TextField()),
                ('authors', models.ManyToManyField(to='search_engine.Author')),
            ],
        ),
        migrations.CreateModel(
            name='DdiFact',
            fields=[
                ('id_fact', models.BigAutoField(primary_key=True, serialize=False)),
                ('numb_sentence_in_doc', models.IntegerField()),
                ('sentence_txt', models.TextField()),
                ('parsing_txt', models.TextField()),
                ('ddi_type', models.TextField()),
                ('id_doc', models.ForeignKey(db_column='id_doc', on_delete=django.db.models.deletion.CASCADE, to='search_engine.ddidocument')),
            ],
        ),
        migrations.CreateModel(
            name='DvaDdi',
            fields=[
                ('id1', models.BigAutoField(primary_key=True, serialize=False)),
                ('id2', models.IntegerField()),
                ('ddi_text', models.TextField()),
                ('pmid', models.IntegerField(db_column='PMID')),
                ('sentencenumb', models.IntegerField(db_column='SentenceNumb')),
                ('finddate', models.DateField(db_column='FindDate')),
            ],
        ),
        migrations.CreateModel(
            name='DvaGisz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('rus', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('eng', models.TextField(blank=True, null=True)),
                ('atx', models.TextField(blank=True, null=True)),
                ('snomed', models.TextField(blank=True, null=True)),
                ('gr', models.IntegerField(blank=True, null=True)),
                ('mnn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportPkgDesc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(blank=True, db_column='SETID', null=True)),
                ('spl_version', models.IntegerField(blank=True, db_column='SPL_VERSION', null=True)),
                ('product_name', models.TextField(blank=True, db_column='PRODUCT_NAME', null=True)),
                ('product_code', models.TextField(blank=True, db_column='PRODUCT_CODE', null=True)),
                ('ndc', models.TextField(blank=True, db_column='NDC', null=True)),
                ('package_description', models.TextField(blank=True, db_column='PACKAGE_DESCRIPTION', null=True)),
                ('form_code', models.TextField(blank=True, db_column='FORM_CODE', null=True)),
                ('product_number', models.IntegerField(blank=True, db_column='PRODUCT_NUMBER', null=True)),
                ('part_yn', models.TextField(blank=True, db_column='PART_YN', null=True)),
                ('total_product_quantity', models.IntegerField(blank=True, db_column='TOTAL_PRODUCT_QUANTITY', null=True)),
                ('strength', models.TextField(blank=True, db_column='STRENGTH', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id_place', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_research', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumb', models.CharField(blank=True, db_column='RegNumb', max_length=255, null=True)),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=255, null=True)),
                ('enddata', models.CharField(blank=True, db_column='EndData', max_length=255, null=True)),
                ('stopdate', models.CharField(blank=True, db_column='StopDate', max_length=255, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('torgname', models.CharField(blank=True, db_column='TorgName', max_length=255, null=True)),
                ('chemname', models.CharField(blank=True, db_column='ChemName', max_length=255, null=True)),
                ('forms', models.CharField(blank=True, db_column='Forms', max_length=255, null=True)),
                ('enterprise', models.CharField(blank=True, db_column='Enterprise', max_length=255, null=True)),
                ('scancode', models.CharField(blank=True, db_column='ScanCode', max_length=255, null=True)),
                ('docum', models.CharField(blank=True, db_column='Docum', max_length=255, null=True)),
                ('pharmgroup', models.CharField(blank=True, db_column='PharmGroup', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DdiResult',
            fields=[
                ('id_fact', models.OneToOneField(db_column='id_fact', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search_engine.ddifact')),
                ('id_task', models.IntegerField()),
                ('id_doc', models.IntegerField()),
                ('sentence_txt', models.CharField(max_length=1024)),
                ('parsing_txt', models.CharField(max_length=1024)),
                ('numb_sentence_in_doc', models.IntegerField()),
                ('ddi_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugLink',
            fields=[
                ('id_fact', models.OneToOneField(db_column='id_fact', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search_engine.ddifact')),
                ('drug_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_back', models.CharField(blank=True, max_length=150, null=True)),
                ('query_text', models.CharField(blank=True, max_length=45, null=True)),
                ('query_time', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True)),
                ('source_id', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, to='search_engine.source')),
                ('username', models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ddidocument',
            name='places',
            field=models.ManyToManyField(to='search_engine.Place'),
        ),
        migrations.AddField(
            model_name='ddidocument',
            name='task_query',
            field=models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, to='search_engine.task'),
        ),
    ]
